Update to SpinalHDL 1.7.0a
Using SpinalCrypto with the original SpinalHDL version leads to strange
issues:

[info] [Progress] at 1.641 : Elaborate components
[error] Exception in thread "main" java.lang.NoSuchMethodError: 'void spinal.core.package$.assert(boolean, scala.Function0)'
[error] 	at spinal.crypto.misc.LFSR$Fibonacci$.apply(LFSR.scala:136)
[error] 	at spinal.crypto.misc.LFSR$Fibonacci$.apply(LFSR.scala:123)

Update to the latest SpinalHDL version.

Signed-off-by: Daniel Schultz <dnltz@aesc-silicon.de>